#!/bin/sh
# Совместимость: делегирует в ssh-pi-proxy.sh.
ROSTER_PI_LAN_HOST="${ROSTER_DOCKER_LAN_HOST:-$ROSTER_PI_LAN_HOST}"
ROSTER_PI_VPS_KEY="${ROSTER_DOCKER_VPS_KEY:-$ROSTER_PI_VPS_KEY}"
ROSTER_PI_VPS_SSH="${ROSTER_DOCKER_VPS_SSH:-$ROSTER_PI_VPS_SSH}"
ROSTER_PI_PORT="${ROSTER_DOCKER_PI_PORT:-$ROSTER_PI_PORT}"
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
exec env \
  ROSTER_PI_LAN_HOST="$ROSTER_PI_LAN_HOST" \
  ROSTER_PI_VPS_KEY="$ROSTER_PI_VPS_KEY" \
  ROSTER_PI_VPS_SSH="$ROSTER_PI_VPS_SSH" \
  ROSTER_PI_PORT="$ROSTER_PI_PORT" \
  "$ROOT/scripts/setup/ssh-pi-proxy.sh"
