events {}

http {
  default_type  application/octet-stream;
  types {
    text/html html;
    text/css css;
    application/javascript js mjs;
    image/svg+xml svg;
    image/png png;
    image/jpeg jpg jpeg;
    application/json json;
    text/plain txt;
  }
  sendfile      on;

  server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
      try_files $uri $uri/ /index.html;
    }
  }
}
